CREATE TABLE IF NOT EXISTS component_update_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component_id BIGINT NOT NULL REFERENCES components(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    serial_number TEXT NOT NULL,
    component_type TEXT NOT NULL,
    manufacturer TEXT NOT NULL,
    status TEXT NOT NULL,
    aircraft_id BIGINT REFERENCES aircraft(id) ON DELETE SET NULL,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE INDEX IF NOT EXISTS idx_component_update_history_component ON component_update_history(component_id, id DESC);
