-- Multi-tenant support.
-- The Super Admin has company_id NULL; all tenant-owned data is scoped by company_id.

CREATE TABLE IF NOT EXISTS companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users ADD COLUMN company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE aircraft ADD COLUMN company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE components ADD COLUMN company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE component_tags ADD COLUMN company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE maintenance_records ADD COLUMN company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE verification_logs ADD COLUMN company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_companies_slug ON companies(slug);
CREATE INDEX IF NOT EXISTS idx_users_company ON users(company_id);
CREATE INDEX IF NOT EXISTS idx_aircraft_company ON aircraft(company_id);
CREATE INDEX IF NOT EXISTS idx_components_company ON components(company_id);
CREATE INDEX IF NOT EXISTS idx_tags_company ON component_tags(company_id);
CREATE INDEX IF NOT EXISTS idx_maint_company ON maintenance_records(company_id);
CREATE INDEX IF NOT EXISTS idx_verification_company ON verification_logs(company_id);
