use crate::{db::DbPool, errors::AppError, models::{ComponentTag, RegisterTagRequest}};

pub struct TagService;
impl TagService {
    pub async fn register_tag(pool: &DbPool, company_id: i64, req: RegisterTagRequest) -> Result<ComponentTag, AppError> {
        let component_exists: Option<(i64,)> = sqlx::query_as("SELECT id FROM components WHERE id = $1 AND company_id = $2")
            .bind(req.component_id).bind(company_id).fetch_optional(pool).await?;
        if component_exists.is_none() { return Err(AppError::ComponentNotFound); }

        let identifier = Self::normalize_identifier(&req.identifier);
        if !Self::valid_hardware_uid(&identifier) {
            return Err(AppError::ValidationError("NFC UID must contain 4 to 10 hexadecimal bytes, for example 04:A1:B2:C3:D4:E5:01".to_string()));
        }

        // A physical NFC UID comes from the tag silicon and must not be
        // regenerated by the app. The database uniqueness constraint is the
        // final protection against binding one physical tag twice.
        let security_type = req.security_type.unwrap_or_else(|| "BASIC_UID".to_string());
        let (id,): (i64,) = sqlx::query_as("INSERT INTO component_tags (component_id, technology, identifier, security_type, tamper_status, company_id) VALUES ($1, $2, $3, $4, 'INTACT', $5) RETURNING id")
            .bind(req.component_id).bind(&req.technology).bind(&identifier).bind(&security_type).bind(company_id)
            .fetch_one(pool).await.map_err(|e| {
                if let sqlx::Error::Database(db) = &e { if db.code().as_deref() == Some("23505") { return AppError::Conflict("This NFC UID is already registered to a component. Each physical tag must have a unique UID.".to_string()); } }
                AppError::DatabaseError(e)
            })?;
        Self::get_tag_by_id(pool, company_id, id).await
    }

    fn normalize_identifier(identifier: &str) -> String {
        identifier.trim().replace('-', ":").to_uppercase()
    }

    fn valid_hardware_uid(identifier: &str) -> bool {
        let parts: Vec<&str> = identifier.split(':').filter(|p| !p.is_empty()).collect();
        matches!(parts.len(), 4..=10)
            && parts.iter().all(|part| part.len() == 2 && part.chars().all(|c| c.is_ascii_hexdigit()))
    }

    pub async fn get_tag_by_id(pool: &DbPool, company_id: i64, id: i64) -> Result<ComponentTag, AppError> {
        sqlx::query_as("SELECT * FROM component_tags WHERE id = $1 AND company_id = $2").bind(id).bind(company_id).fetch_optional(pool).await?.ok_or_else(|| AppError::NotFound("Component tag not found".to_string()))
    }

    pub async fn get_tag_by_identifier(pool: &DbPool, company_id: i64, identifier: &str) -> Result<ComponentTag, AppError> {
        let normalized = Self::normalize_identifier(identifier);
        sqlx::query_as("SELECT * FROM component_tags WHERE identifier = $1 AND company_id = $2").bind(&normalized).bind(company_id).fetch_optional(pool).await?.ok_or_else(|| AppError::NfcTagNotRegistered)
    }
}
